### PR TITLE
Eliminate unwanted order routes

### PR DESCRIPTION
**Pull request by bbuchalter**
This bumps the routes file of 2-1-stable branch upto master which is what Solidus is
based on and is effectively the same.

To support https://github.com/TommyJohnWear/tommyjohn/pull/1830

### CODE REVIEW

**Comment by gmacdougall** [comment]
We probably don't want any of those routes. I don't think we want them in solidus_gateway either. They're crazy.

**Comment by bbuchalter** [comment]
I have to agree. Let's chat about how we'll take care of that.

**Comment by bbuchalter** [comment]
@gmacdougall and I discussed and agreed it's out of scope of this story to do the skrill cleanup, although it probably should happen in `solidus_gateway`.

**Comment by stewart** [comment]
:+1:

**Pull request merged**
